### ISSUE TITLE
GROUP in its final shape

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/GMQL#75]
After agreeing with StefanoC and Olya, we have disambiguated the aspects of syntax/semantics of Group that were still unclear.

Changes needed on the COMPILER level: @pp86 

1.  _meta_aggregates_ must compute aggregates on **metadata attributes**, not region attributes as it is right now
1. we must decouple the definition of grouping attributes (both region and metadata) and the computation of aggregates. Currently it is not possible to write GROUP(region_keys: x) without using also the _region_aggregates_ parameter. Also, it is not possible to write GROUP(<metadata_attribute>) without using also the _meta_aggregates_ parameter. Instead, we want to be able to do that: just grouping without computing (adding) new attributes.
1. we want to be able to eliminate duplicated regions (with the same _char,start,stop,strand_) without computing any aggregate. Currently, this is not possible. We propose to do this using a syntax like: GROUP(region_keys: default), or GROUP(region_keys: ), or GROUP(region_keys: chr,start,stop,strand). @pp86 here you should choose/propose what you think is best.
1. default GROUP() should not be allowed
1. We must only allow ONE metatada grouping attribute at a time (now multiple are allowed)
1. If I use the aggregation function COUNT() in the option _meta_aggregates_ it should calculate the number of samples forming the identified group. E.g., GROUPS_C = GROUP(cell; meta_aggregates: n_samp AS COUNT()) EXP; --> In sample x, the metadata _n_samp_ should contain the number of samples belonging to the group of sample x (formed based on the grouping attribute _cell_)

Changes needed on the IMPLEMENTATION level: @OlgaGorlova @akaitoua 

1.  _meta_aggregates_ must compute aggregates on **metadata attributes**, not region attributes as it is right now
1. Currently, when a grouping metadata attribute is not present in a sample, that sample is returned unchanged. We want it to have the _group new attribute with the "special" value 0. Also in this case meta_aggregates must be computed
1. Currently, if we use a GROUP statement on a dataset which already presents __group_ metadata attributes (because it is itself the output of a previous GROUP statement), we add an additional __group_ metadata, with no connection with the previous one. Now we want the __group_ to be recomputed from scratch [this follows from the fact that from now on the GROUP will only be able to work on ONE metadata grouping attribute at a time].
1. Fix __group_ strange numbering

For whoever can fix this (if it hasn't already): @pp86 @OlgaGorlova @akaitoua 

1. In _region_aggregates_ it calculates the SUM of scores instead of AVG (now in the metadata_aggregates it works correctly)

**Comment by pp86** [comment]
I implemented the compiler changes and a skeleton of the metadata aggregate function infrastructure.

Please, @OlgaGorlova find the changes in the following branch:
https://github.com/DEIB-GECO/GMQL/tree/group_redefined

**Comment by OlgaGorlova** [comment]
I implemented metadata aggregate functions. I am not sure what functions should it have, but here is a list of implemented functions: COUNT, SUM, MIN, MAX, AVG, BAG, BAGD. 

@pp86, I committed changes to https://github.com/DEIB-GECO/GMQL/tree/group_redefined.

**Comment by marcomass** [comment]
@OlgaGorlova 
Please implement the use of all aggregate functions (i.e., including also MEDIAN e STD) in GROUP metadata aggregate. 
All aggregate functions (i.e., COUNT, SUM, MIN, MAX, AVG, BAG, BAGD, MEDIAN and STD) should also be usable in GROUP for region aggregate.
@akaitoua, @pp86

**Comment by OlgaGorlova** [comment]
@marcomass, MEDIAN and STD have been added.

@pp86, can you please introduce all these functions in the compiler?

**Comment by sunbrn** [comment]
@OlgaGorlova can you please fix also point 4 (you told me the first three assigned to you are ok now)
About point 3, just to make sure we are on the same page: in each group there should be always only 1 attribute __group_ for each sample. This means that the attribute should be overwritten if it already exists. Is it like that?

@pp86 are you in charge of merging the branch were these modifications are?

**Comment by pp86** [comment]
@OlgaGorlova Functions should be "automatically" added (the function name is passed down to the factory). I tried a couple of them and I see no problem, have you encountered any?

@sunbrn  I merged the two branches

**Comment by OlgaGorlova** [comment]
@pp86, thanks! I did not see problems with functions so far.

**Comment by OlgaGorlova** [comment]
@sunbrn 
Point 4 is fixed now. About point 3, yes, it works like you described.

**Comment by sunbrn** [comment]
@pp86 
Point 3 still needs to be fixed.

@OlgaGorlova
- Pietro fixed this: "The compiler does not allow to specify a grouping attribute without specifying any meta_aggregates" but now I get a DS_CREATION_FAILED
- Point 2 is not solved, because the special value _group=0 is assigned to a group which DOES HAVE the grouping metadata attribute. It should be assigned to a group of samples that do not have it.

@pp86 @OlgaGorlova @marcomass 
- In meta_aggregates the aggregation function COUNT() does not make any sense. Instead we could have a COUNTSAMP() calculating the number of samples belonging to that group. Is this possible to implement? Or should we just eliminate the COUNT() from the meta_aggregate part?

**Comment by OlgaGorlova** [comment]
@sunbrn 

> Pietro fixed this: "The compiler does not allow to specify a grouping attribute without specifying any meta_aggregates" but now I get a DS_CREATION_FAILED

> Point 2 is not solved, because the special value _group=0 is assigned to a group which DOES HAVE the grouping metadata attribute. It should be assigned to a group of samples that do not have it.

fixed

**Comment by OlgaGorlova** [comment]
@sunbrn @marcomass @pp86 
I have changed COUNT() to COUNTSAMP(). It now calculates the number of samples in a group.

**Comment by sunbrn** [comment]
Great @OlgaGorlova !

Please @pp86 let me know when the region_keys part is fixed, 
and please @acanakoglu let me know when the version with all these changes is up on the interface.

This is the last missing thing to finish the GMQL manual :)

**Comment by pp86** [comment]
@OlgaGorlova 
I modified the operator according to the requests. Now the coordinates have to be passed by the user; those are passed down to the implementation as instances of:
COORD_POS.CHR_POS/LEFT_POS/RIGHT_POS/STRAND_POS

If not specified, the group should not consider their values when grouping.

**Comment by pp86** [comment]
@sunbrn: it is possible to group only on region coordinates by not using the 'region_keys'

**Comment by sunbrn** [comment]
Things that I would like to be sorted out with the help of @pp86  and @marcomass 

- It is not possible to only aggregate without calculating any new aggregate (maybe this could be possible by allowing the GROUP() that we had in the beginning?)

- If I calculate D = GROUP(region_keys: fifth; region_aggregates: newAtt AS SUM(score)) C; in the output samples I see the regions correctly grouped but the additional grouping attribute “fifth” is not included, while the 4 coordinates and the aggregated function “newAtt” are correctly included
Similarly, if I use D = GROUP(region_keys: fifth) C, in the output “fifth” never appears in the samples (although correctly used to compute the result)

- If I use D = GROUP(region_keys:ciao; region_aggregates: newatt AS SUM(ciao)) C; the compiler and execution work correctly. Although, I should not be able to aggregate on an attribute used to group.

- I used the query: 
E = SELECT() DS_in;
D = GROUP(cell)E;
DS_in has schema chr,left,right,strand,name,score (and accordingly its samples have 6 coordinates). But, after using GROUP, the schema in dataset D is set to chi,left,right,strand (but samples have correctly 6 coordinates). What went wrong in this schema?

**Everything else now looks correct to me, according to the initial agreed definition of the operator.**

**Comment by sunbrn** [comment]
@OlgaGorlova this should be on your side

If I calculate D = GROUP(region_keys: fifth; region_aggregates: newAtt AS SUM(score)) C; in the output samples I see the regions correctly grouped but the additional grouping attribute “fifth” is not included, while the 4 coordinates and the aggregated function “newAtt” are correctly included
Similarly, if I use D = GROUP(region_keys: fifth) C, in the output “fifth” never appears in the samples (although correctly used to compute the result)

**Comment by sunbrn** [comment]
@pp86, can you please fix these two things?

- It is not possible to only aggregate without calculating any new aggregate (maybe this could be possible by allowing the GROUP() that we had in the beginning?)

- I used the query: 
E = SELECT() DS_in;
D = GROUP(cell)E;
DS_in has schema chr,left,right,strand,name,score (and accordingly its samples have 6 coordinates). But, after using GROUP, the schema in dataset D is set to chr,left,right,strand (but samples have correctly 6 coordinates). What went wrong in this schema?
[group_meta1_20171214_123952_RESULT.zip](https://github.com/DEIB-GECO/GMQL/files/1559023/group_meta1_20171214_123952_RESULT.zip)
[group_meta1_20171214_123952_INPUT.zip](https://github.com/DEIB-GECO/GMQL/files/1559024/group_meta1_20171214_123952_INPUT.zip)

**Everything else now looks correct to me, according to the initial agreed definition of the operator.**

**Comment by OlgaGorlova** [comment]
@sunbrn, fixed. Now grouping attributes are included in output.
